# Generated by Django 2.2.7 on 2019-11-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMarca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRopa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRopa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=20)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], default='M', max_length=1)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Marca')),
                ('TipoRopa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.TipoRopa')),
            ],
        ),
    ]
