# Generated by Django 2.2.7 on 2019-11-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=50)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Rut', models.IntegerField(max_length=8)),
                ('Telefono', models.IntegerField(max_length=10)),
            ],
        ),
    ]
